### ISSUE TITLE
Remove OpenGL-Registry submodule?

### ISSUE THREAD

**Issue by silversquirl** [ziglibs/zgl#51]
It's not required for the bindings to operate, seems to just be for reference purposes?
Having it submoduled makes things annoying for projects that incorporate zgl as a submodule, since cloning them recursively pulls in almost 180MB(!!) of XML.
Might make more sense to just gitignore it so people can clone it into the zgl dir if they want to.

**Comment by ikskuh** [comment]
Feel free to make a PR that does this.
