### ISSUE TITLE
Code won't build with latest 0.11 version of Zig

### ISSUE THREAD

**Issue by mondegreengames** [ziglibs/zgl#81]
A recent update to Zig 0.11 (https://github.com/ziglang/zig/pull/16046) has broken a lot of code in zgl with renames like `@intToFloat()` to `@floatFromInt()`.

**Comment by mondegreengames** [comment]
Does zgl try to stay compatible with the latest stable (0.10.1) or with the latest pre-release (0.11)? Maybe the master branch could be latest-stable-compatible and a separate dev branch tries to keep up with pre-release?

**Comment by ikskuh** [comment]
i'm tracking master till 0.11 release, after that i'll completly rely on community updates

**Comment by mondegreengames** [comment]
PR https://github.com/ziglibs/zgl/pull/80 fixed my original issue, then Zig changed several casts in https://github.com/ziglang/zig/pull/16163, and that is what the above PR fixes.
